### ISSUE TITLE
per_page filter broken

### ISSUE THREAD

**Issue by developer-lindner** [WP-API/WP-API#2757] opened 2016-10-04 06:50 UTC
class-wp-rest-posts-controller.php

Line 129:

```
// Ensure our per_page parameter overrides filter.
$args['posts_per_page'] = $request['per_page'];
```

This ensures nothing!
It just overrides the given value with your default of 10. Congrats!

Do you even test this stuff before releasing it? This broke our clients most important feature.
Thank you very much! -.-

I don't even get it we you introduce another parameter instead of using just 'posts_per_page' as before...

**Comment by kadamwhite** [comment] 2016-10-04 10:52
@developer-lindner Thanks for raising the issue; I'm not sure I understand exactly what the problem you're describing is, can you explain the specific request you are making that no longer works? `per_page` is the proper way to specify the number of results to include in a response, and can be set to any value from 1 to 100; this most recent beta did introduce a breaking change to fully deprecate `filter[posts_per_page]`, which could not be properly validated to fit within this range and incorrectly exposed a bug that allowed out-of-bound values to be sent through with the query, causing performance issues with large sites. In general if there is a first-party query parameter available for a request property it should always be used in place of `filter`. 

Looking at the release post we did not highlight breaking changes in this plugin beta; **this was a _huge_ oversight** and I will ensure we do better in subsequent releases.

If you can provide more information we can validate whether the behavior you are describing is a bug, or a result of the removal of `filter[posts_per_page]`. Thanks

**Comment by developer-lindner** [comment] 2016-10-04 13:05
@kadamwhite I do understand your concerns and your intention. well, after updating to latest version i've received 10 instead of 54 items. because this one particular line overrides my value of -1 with the default value of 10.

The request looks like this: wp-json/wp/v2/types?filter[posts_per_page]=-1&filter[lang]=...

Which broke as i said.

**Comment by kadamwhite** [comment] 2016-10-04 13:17
@developer-lindner In your case I recommend switching immediately to

```
?per_page=100&filter[lang]=...
```

`-1` cannot be supported due to the performance impact it represents for large sites; this seems like an inconvenience for the client developer, but despite HTTP latency it is much more efficient (and much less impactful on your server and database) to request multiple small pages and then assemble them into one collection within the requesting application than it is to request one page of results containing all content.

I am going to close this issue because the API is working as designed, if not as expected or desired. I do sincerely apologize for our failure to call out this breaking change.

**Closed as completed by kadamwhite** 2016-10-04 13:17 UTC
