### ISSUE TITLE
Warning in create comment response

### ISSUE THREAD

**Issue by ssmagin** [WP-API/WP-API#2310] opened 2016-02-24 11:01 UTC
When I create comment, for example:

> curl -i --data "post=11285&author_name=sergey&author_email=test@test.com&content=test_comment_3" http://blog.lo/wp-json/wp/v2/comments

I receive

```
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/nas/content/staging/kasperskyhub/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-comments-controller.php</b> on line <b>73</b><br />
```

**Comment by ocean90** [comment] 2016-02-24 11:02
Duplicate of #2260.

**Comment by danielbachhuber** [comment] 2016-02-24 12:43
To fix your problem until the next beta, you can apply 80dcacf95140a445d262aefb55d1054ee2750108 locally.

**Closed as completed by danielbachhuber** 2016-02-24 12:43 UTC
