### ISSUE TITLE
Why do we allow changing the post type of a post

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#884] opened 2015-02-15 17:04 UTC
Given that we are potentially exposing different schema for different post types, it has some weird behaviour if you switch a post between post types. It seems we should not allow this, also we should throw a 404 for `/wp/posts/123` if 123 is a page, which we currently don't I think.

**Comment by danielbachhuber** [comment] 2015-02-15 17:33
:+1:

**Comment by joehoyle** [comment] 2015-02-15 19:01
Code in question: https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-posts-controller.php#L414

**Comment by rachelbaker** [comment] 2015-02-15 19:03
We didn't used to allow it: https://github.com/WP-API/WP-API/commit/40d984e9aca50ab7ee6023c12ae2324a81d2c4a4

**Comment by rmccue** [comment] 2015-02-16 01:52
:+1:

Looks like we don't allow it, as per @rachelbaker's comment above. Close?

**Comment by joehoyle** [comment] 2015-02-16 02:14
@rmccue seems there is some code here that should maybe be removed? https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-posts-controller.php#L414 I think I can into this somehow - maybe setting type on create rather than update or something.

**Comment by rmccue** [comment] 2015-02-16 02:15
I think that's only meant to run on create; that method is shared by both update and create.

**Comment by joehoyle** [comment] 2015-02-16 02:16
Right, but the post type enforcement is only in `update_item` I think

**Comment by rachelbaker** [comment] 2015-02-16 16:36
@joehoyle @danielbachhuber @rmccue What about setting the default 'type' to the post type in the 'create' route registration args?  If I send a POST request to `/wp/pages/` I would expect to create a page, and not have to specify the `type`.

**Comment by joehoyle** [comment] 2015-02-16 18:03
@rachelbaker right - IMO `type` is immutable, just like you don't set "status" when you create a comment etc.

**Comment by danielbachhuber** [comment] 2015-02-16 20:15
Yes, I should think the post type should be tied to the route immutably, when creating or updating. If someone wants to be able to switch post types, they can do so with their own endpoint. It isn't a behavior we should support with core endpoints (just as the admin doesn't currently support this)

**Comment by rachelbaker** [comment] 2015-02-16 21:08
@danielbachhuber The only regression I see is that previously you could get the `/posts/` endpoint and return a query from an array of post_types.  Example:  `GET /posts?type[]=post&type[]=page`

**Comment by danielbachhuber** [comment] 2015-02-16 21:23
Not a regression. That's how 1.0 worked. 2.0 will work differently. If a developer needs that for her bespoke project, she can write an endpoint

**Comment by rachelbaker** [comment] 2015-02-16 21:55
@danielbachhuber :100: points for using `developer` with  the **her** pronoun.

**Comment by rachelbaker** [comment] 2015-02-16 22:02
@rmccue Any concerns with backwards compatibility?  For a "feature regression" (or something that could be viewed as such, like this) do we need to bring it to the attention of anyone else (Dion, Nacin, etc)?

**Comment by danielbachhuber** [comment] 2015-02-22 20:02
Couple of changes:

1. #908 will throw a 404 if you try to access a Post through a Page endpoint.
1. #913 always defers to the controller for the post type, and ignores `type` argument present in `POST` or `PUT` request

I merged the first because I haven't seen any disagreement on its behavior. I'll leave the second as a #reviewmerge for a second opinion.

**Closed** 2015-02-23 19:40 UTC
Labels: Bug
