### ISSUE TITLE
Options Endpoints

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#816] opened 2015-01-28 11:49 UTC
Given that the API will be used for more than just WordPress data objects, I thought it would be good to discuss how we would implement Options Endpoints and then if all goes well, have a go an implementing it. This is something we'd need in say, supporting the WP-Admin via the API. Option ID seems like something we'd want to remove too.

### Abstraction

I'm not currently sure how much abstraction we would want to provide for options. I might not be realistic to get a schema driven interface for options (but it would be cool), as the underlying core api is so loose and lenient. It would seem likely that we would want to support all the core options in some more meaning full way however. For example, take an option that has a date stored in format `x`, we'd presumably want standard date formats across the API and would therefore perhaps transforms these things. We'd only be able to do that on inbuilt options as we'd need to define it.

### Types

An option value can be of arbitrary type, which means we can't do much to document and enforce types. The type of a single option can change, say from a string to an int. It would be nice to support all the inbuilt options in with validation etc, but this would require a pretty hefty array of hardcoded schema for options that doesn't currently exist in core. For example, do we allow updating `siteurl` to `true`? 

Autoloading is something that would be nice to hide away, but not sure if there is valid use cases for exposing it.

### Permissions

It seems all options are managed under the `manage_options` capability - though I'm not sure if there are meta caps on that, doesn't seem so. However, core allows modification of the required capability on a per-subpage basis via `option_page_capability_{$option_page}`. 

### Routes

I considered including the option group name or something in the route, but I think that's probably not a good idea now. It seems that just one at `/wp-json/options/$option_name` would be enough.

```
GET     /wp-json/options/siteurl
DELETE  /wp-json/options/siteurl
POST    /wp-json/options/siteurl
```

### Object Schema

Based of information we can get, I think we'd need more information in an object that just the value it's self as the object.

```
{
    name: "siteurl",
    value: mixed,
    autoload: bool
}
```

Alternatively, we could just have the value as the object it's self, though that exposing issues with arrays etc being the direct response.

### Schemas

The options may not initially seem like they are schema based, however a bunch of the stuff proposed in #759 would be pretty cool - especially around defining enums etc. With options that are arrays/objects etc, we could use that schema to markup the full object in the option value too. `wp-admin/options.php` really sucks because it has no inference of the data types etc of the options. It would be pretty cool if we could get all the goodness proposed in #759 for options (if said path is chosen).

The most simple hack here is to wrap `get/update/delete_option`, technically, that would work - but that's no an API! I think we can do a lot better than that. It may require a bunch of hardcoding for core options, and providing hooks etc for custom options, but I think it can be done.

**Comment by danielbachhuber** [comment] 2015-01-28 13:11
One quick thought: what if the explicit way of thinking about this endpoints was *access to do anything you can do in the admin* not *edit anything you can edit in the darabase*?

For the former, the problem becomes much easier to solve: we have a site object with certain, much more limited attributes (name, description, active_theme), and we don't need to worry about auto loading, option names, etc

**Comment by rmccue** [comment] 2015-01-29 01:37
> For the former, the problem becomes much easier to solve: we have a site object with certain, much more limited attributes (name, description, active_theme), and we don't need to worry about auto loading, option names, etc

Totally agree with this. Options are the underlying data model, but they're just a key-value store. Instead, we should think about site resources with properties.

Bonus: scales up to multisite. :)

**Comment by danielbachhuber** [comment] 2015-02-02 03:51
> Instead, we should think about site resources with properties.

This is going to be so hawt.

**Comment by EdHurtig** [comment] 2015-02-24 15:14
I would love to lend a hand with this as well. I have wanted to see an options endpoint in the WP-API for a while now and gave it a try in #432, but that PR was pretty old and a lot has changed since I wrote it. Let me know if you want me to start working on this, I don't want to step on anyone's toes though.

**Comment by jtsternberg** [comment] 2015-02-25 16:02
Curious about the security implications here since the options table holds a lot of sensitive data. Would this be an authenticated request?

**Comment by EdHurtig** [comment] 2015-02-26 03:04
This **must** be an authenticated endpoint, but to be more specific, the authenticated user would have to hold the `manage_options` capability and/or possibly the `option_page_capability_{$option_page}` (see the Permissions section in the Description)

**Comment by jtsternberg** [comment] 2015-02-26 03:15
Ah, yes, should have read more carefully. Good to hear.

**Comment by Ramblurr** [comment] 2015-02-26 08:41
Not sure if I understand @EdHurtig 's comment entirely, but I have usecases where some custom options data should not be authenticated.

For example, when a user wants to create an admin options page to edit and expose custom data via JSON that doesn't fit into the post, page, or taxonomy buckets. 

Then again maybe you're just referring to actual admin options, which definitely should be authenticated.

**Comment by rmccue** [comment] 2015-02-27 02:41
@EdHurtig is correct; whatever *generic* options endpoints we end up with need to be authenticated, and checked against the `manage_options` capability.

It'll also need to follow the rules for meta, in that we cannot send or accept serialized data, nor allow any modifications to any existing serialized options. This is a fundamental requirement caused by the JSON serialization we use.

> Not sure if I understand @EdHurtig 's comment entirely, but I have usecases where some custom options data should not be authenticated.

If there are specific options that fit into this pattern, likely your best option will be a custom endpoint rather than using the generic ones. That said, we may be able to achieve more granular (filterable) permissions that would allow this.

**Comment by EdHurtig** [comment] 2015-03-03 17:12
I agree with @rmccue, Your best bet is either a custom endpoint. However, I really like the idea of adding more granular and filterable permissions for each option. Unfortunately, I do not believe there are any meta capabilities for options, unlike posts which you can check with lines like: `current_user_can( 'edit_post', 12 )`

**Comment by EdHurtig** [comment] 2015-03-03 17:18
@rmccue Too bad that serialized data has to be a no-go. Ran into that in 432 too and was very :disappointed:

**Comment by rmccue** [comment] 2015-03-05 00:07
> @rmccue Too bad that serialized data has to be a no-go. Ran into that in 432 too and was very :disappointed:

Indeed, it's been one of the biggest issues with meta, and it's pretty :poop:. Unfortunately, serialized data is super unsafe to handle. :(

**Comment by EdHurtig** [comment] 2015-03-05 17:04
Alright well I will try to catch up to speed on the current design practices for WP-API and take a swing at this hopefully this weekend with the rough specs we have outlined already.

The `add_option` and `update_option` perform two somewhat different operations, would it be best to have `POST` and `PUT` endpoints that map to those operations? or do we just want to have `POST` map to `update_option` which is what seems to be outlined in the **Routes** section of the issue

**Comment by rmccue** [comment] 2015-03-06 01:45
In general:
```
GET    /<object>      - List of all <object>s
POST   /<object>      - Create <object>

GET    /<object>/<id> - Get singular <object>
PUT    /<object>/<id> - Update singular <object>
DELETE /<object>/<id> - Delete singular <object>
```

The main unanswered question here so far is whether we want these to exist as independent resources (ala meta) or just as properties on a site object. Meta exists as separate objects, but that's because they're more than just a key-value store, whereas options are just kv for a site.

Do we need to differentiate between `add_option` and `update_option`? I don't think so, so I think it makes more sense to expose on a site object rather than independent resources.

**Comment by danielbachhuber** [comment] 2016-01-30 17:42
Closing in favor of future development in https://github.com/WP-API/wp-api-site-endpoints

**Closed by danielbachhuber** 2016-01-30 17:42 UTC
Labels: #Blessed, Enhancement
