### ISSUE TITLE
rest_no_route returned on non-main network sites

### ISSUE THREAD

**Issue by richardtape** [WP-API/WP-API#1952] opened 2016-01-05 18:51 UTC
*Setup*: Sub-directory WordPress Multisite install with JJJ's [wp-multi-network plugin](https://github.com/stuttter/wp-multi-network). New networks of sites have been created on a subdomain basis. Currently running WordPress trunk (so no WP-API plugin active) but the same thing happened with 4.3 and the WP-API plugin active. JJJ's plugin has been both active and inactive in these tests with the same result). No other plugins. 2016 Theme.

The 'main' network (`site_id` = 1, `blog_id` = 1, `path` = /, `domain` = domain.dev from `wp_blogs` table) is at http://domain.dev. A site on that network (`site_id` = 1, `blog_id` = 2, `path` = /site-name/ ) is at http://domain.dev/site-name/ .
A separate network has been created (`site_id` = 2, `path` = /, `domain` = network2.domain.dev) and a site added to that network (`site_id` = 2, `path` = network2site, `blog_id` = 4)

*Expectation*: Making a `GET` request to any of the following URLs would return the posts for the site domain.dev/wp-json/wp/v2/posts, domain.dev/site-name/wp-json/wp/v2/posts, network2.domain.dev/wp-json/wp/v2/posts and network2.domain.dev/network2site/wp-json/wp/v2/posts

*Actual result*: The main network site and any sub-site of the main network return the posts as expected (i.e. site_id = 1, blog_id = 1 and 2). However, any site on a different network, including a network's main site (i.e. the one auto-created when a new network is made) always returns `{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}` (i.e. site_id != 1 and blog_id = *)

I've flushed permalinks on all sites to no avail (I was _so_ certain that would fix it, it normally fixes things ;) ). I've also asked nicely, sacrificed a goat (not my pet goat, Betty, that would be wrong) and prayed to all known deities and even to others I've made up.

I genuinely have no idea where to start debugging this. Happy to throw anything your way or do anything I can to help.

**Comment by danielbachhuber** [comment] 2016-01-05 18:56
On the subsite of the second network:

* Is the WP-API plugin active?
* Do normal posts and pages load as expected?

**Comment by richardtape** [comment] 2016-01-05 19:05
Everything works as per normal on the subsites. The plugin isn't active - I'm running WP Trunk. Beforehand (pre 4.4) it was network activated.

**Comment by richardtape** [comment] 2016-01-05 19:38
I'm on the Post Status slack by the way if that's easier/faster to get me to jump through some hoops.

**Comment by richardtape** [comment] 2016-01-05 22:13
I just want to add that the same behaviour is apparent with version 1.2.4 of the plugin (network activated) and 2.0-beta9 (also network activated)

**Comment by danielbachhuber** [comment] 2016-01-07 14:20
I'll debug when I have some time to mirror the environment.

**Comment by richardtape** [comment] 2016-01-07 16:10
Hey @danielbachhuber, thanks that's great. If there's any sort of hint you can give me as to where you'd start with this, I'm happy to jump right in and see what I can do. I'm seriously new to this plugin (I know, I know, I should have been using it for months ;) ) but more than happy to help where I can here.

**Comment by danielbachhuber** [comment] 2016-01-11 22:19
I tried reproducing today and wasn't able to. Here's a few screenshots of my configuration, and the results I get:

![image](https://cloud.githubusercontent.com/assets/36432/12248344/95af5e72-b86d-11e5-9545-7b959dc4a0f6.png)

![image](https://cloud.githubusercontent.com/assets/36432/12248350/9da07ac6-b86d-11e5-9b99-d1826d9fbe5d.png)

![image](https://cloud.githubusercontent.com/assets/36432/12248357/af97b3c0-b86d-11e5-97c9-87434365a148.png)

![image](https://cloud.githubusercontent.com/assets/36432/12248369/c79916f8-b86d-11e5-98f1-25bcf977b8ee.png)

I can't think of anything where the network would impact REST API routing. It would be good to get more details on your implementation, and any additional debugging you can do.

**Comment by jessertaylor** [comment] 2016-01-13 11:33
I'm having a similar issue. I'm having issues with the /terms endpoint. This works fine locally on a non-multisite install, but on a live multisite install it gives a 404.

For example this works fine locally (non-multisite) but does not work on multisite.

http://www.domain.com/wp-json/wp/v2/terms/my_taxonomy_name

I have discovered if I remove /terms then it works on the multisite but not locally on the non-multisite eg

http://www.domain.com/wp-json/wp/v2/my_taxonomy_name

This seems to be a new bug as everything was working until I presume the plugin got updated.

**Comment by mistvan** [comment] 2016-01-21 08:33
Hi guys, 
I have subsite spevnik and song custom post type there http://mistvan.spolocenstvomajak.sk/spevnik/wp/v2/song. Result is not correct.

But using `rest_route=/wp/v2/song` param saved me :)
http://mistvan.spolocenstvomajak.sk/spevnik?rest_route=/wp/v2/song

Thanks

**Comment by danielbachhuber** [comment] 2016-01-22 01:26
@richardtape I'm going to close this for now — feel free to re-open if you are able to successfully reproduce.

**Closed by danielbachhuber** 2016-01-22 01:26 UTC
Labels: Support
