### ISSUE TITLE
<style> in header weirdness

### ISSUE THREAD

**Issue by modemlooper** [WP-API/WP-API#1414] opened 2015-07-22 14:44 UTC
This has happened on a  few sites where they have style at the very top of their head section and it breaks the json. Anybody else have this happen? http://www.justforhearts.org/wp-json/posts/?type=product

**Comment by modemlooper** [comment] 2015-07-22 14:50
![head](https://cloud.githubusercontent.com/assets/867885/8828294/a6e6586e-304e-11e5-85b8-7d5eba19f8a3.png)

![json](https://cloud.githubusercontent.com/assets/867885/8828299/aa37e442-304e-11e5-977a-8169a6187ecb.png)

**Comment by rmccue** [comment] 2015-07-22 15:20
How are you outputting this style tag? I suspect you're using the wrong hook.

**Comment by modemlooper** [comment] 2015-07-23 15:49
not me, was on a couple sites. Just thought it was weird it would show in the json response.

**Comment by rmccue** [comment] 2015-07-24 10:46
Definitely seems like the wrong hook, possibly people outputting on `template_redirect` for older versions of the API. Closing for now, but reopen if you can reproduce and it turns out to be a bug. :)

**Closed by rmccue** 2015-07-24 10:46 UTC
Labels: Reporter Feedback, Support
