### ISSUE TITLE
Include Single Post pagination _links

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#866] opened 2015-02-10 03:10 UTC
Add "previous" and "next" _link objects for single pagination.

**Comment by joehoyle** [comment] 2015-02-10 14:47
What is "next" though? By chronology? Getting a single post object (presuming what this is for) I don't know exactly what "pagination" means

**Comment by rmccue** [comment] 2015-02-11 11:42
> What is "next" though? By chronology? Getting a single post object (presuming what this is for) I don't know exactly what "pagination" means

The same as the logic used by `get_adjacent_post_rel_link` in core, which adds `rel="next"` and `rel="prev"` to single post views in HTML (see `adjacent_posts_rel_link_wp_head`).

**Comment by rmccue** [comment] 2015-02-11 12:25
Closing as duplicate of #783.

**Closed by rmccue** 2015-02-11 12:25 UTC
Labels: Enhancement
