### ISSUE TITLE
`filter` param for Users, Comments and Terms

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2066] opened 2016-01-21 14:30 UTC
We have a `filter` param on `GET /wp/v2/posts` which permits clients to use `WP_Query` arguments.

Should we introduce an equivalent param for Users, Comments and Terms?

If we do, we'll need a layer of authorization to use the `filter` param, as core currently doesn't have a paradigm of public vs. private query vars for non-Posts.

**Comment by kadamwhite** [comment] 2016-01-22 17:47
If we provide a `slug` query parameter across relevant collection types, looking at `get_terms` much of the remaining functionality is actually replicated by the existing parameters `page`, `per_page`, `order`, etc. The main pieces of term-specific functionality that isn't supported by the current parameters (per #924 at least) is searching by Slug, as noted in #2065; `child_of`, which extends beyond what the `parent` property can do; the `*__like` methods; and `exclude_tree`. These would make sense to expose via `filter`, but the functionality that's replicated by api-specific parameters wouldn't need to be exposed via the `filter` shim.

> we'll need a layer of authorization

I do not think this will be a good user experience; I either think we should whitelist some keys and provide them publicly with no auth needed, or not pursue the filter parameter at all. I believe API users will just be frustrated if they have to authenticate to make a `child_of` or `slug` query, without caring about the nuance of why that is the case.

**Comment by danielbachhuber** [comment] 2016-01-22 17:58
> > we'll need a layer of authorization
> 
> I do not think this will be a good user experience; I either think we should whitelist some keys and provide them publicly with no auth needed, or not pursue the filter parameter at all.

It's not really a user experience consideration — it's a "are we exposing data that was previously private" consideration.

**Comment by kadamwhite** [comment] 2016-01-22 18:29
I don't mean to discount that, but I'd rather a custom slug parameter that I can use than a filter parameter that requires authentication.

Additionally, most of the properties I described could be deduced as-is by iterating through all terms and computing the relationships yourself; that's just horribly inefficient.

**Comment by patrickgalbraith** [comment] 2016-01-24 06:15
Some reference for the built in queries and the equivalent API parameters currently.

## WP_Comment_Query

https://codex.wordpress.org/Class_Reference/WP_Comment_Query

| Key | API |
| --- | --- |
| author_email | author_email |
| author__in |  |
| author__not_in |  |
| include_unapproved |  |
| fields |  |
| ID | id |
| comment__in | include |
| comment__not_in |  |
| karma | karma |
| number |  |
| offset |  |
| orderby | orderby |
| order | order |
| parent | parent |
| post_author__in |  |
| post_author__not_in |  |
| post_id | post |
| post__in |  |
| post__not_in |  |
| post_author | post_author* |
| post_name | post_slug* |
| post_parent | post_parent* |
| post_status | post_status* |
| post_type | post_type* |
| status | status |
| type | type |
| type__in |  |
| type__not_in |  |
| user_id | user |
| search |  |
| count |  |
| meta_key |  |
| meta_value |  |
| meta_query |  |
| date_query |  |

## WP_User_Query

https://codex.wordpress.org/Class_Reference/WP_User_Query

| Key | API |
| --- | --- |
| role |  |
| include | include |
| exclude |  |
| blog_id |  |
| search | search |
| search_columns |  |
| number |  |
| offset |  |
| orderby | orderby |
| order | order |
| date_query |  |
| meta_key |  |
| meta_value |  |
| meta_compare |  |
| meta_query |  |
| who |  |
| count_total |  |

**Comment by danielbachhuber** [comment] 2016-01-24 14:11
@patrickgalbraith Thanks for putting together the chart. You can track our progress on adding query params in #924, though there's a couple things to note:
1. We won't be able to implement 100% parity with `WP_Comment_Query` and `WP_User_Query`, because some features don't make sense in REST API context.
2. As much as possible, we want to normalize parameters and usage.

**Comment by msankar1991** [comment] 2016-05-12 12:06
Hi Team,

I'm using this wp rest api with my website for filter custom meta fields called price. So here need to filter the data used price range for this examples:

`http://192.168.0.101:8383/wp-json/wp/v2/posts/?filter[meta_query][0][key]=price&filter[meta_query][0][value][0]=50&filter[meta_query][0][value][1]=200&filter[meta_query][0][compare]=between`

`http://192.168.0.101:8383/wp-json/wp/v2/posts/?filter[meta_key]=price&filter[meta_value][0]=50&filter[meta_value][1]=200&filter[meta_compare]=between`

Above both examples not getting exact match results to me. And i've added & using the custom `rest_query_vars` process only. 

```
add_filter('rest_query_vars', 'custom_rest_query_vars');
function custom_rest_query_vars($query_vars) {
    $query_vars = array_merge( $query_vars, array('meta_key', 'meta_value', 'meta_compare','meta_query') );
    //print_r($query_vars);exit;
    return $query_vars;

}
```

And also its working with greater than or less than custom fields below example for reference.

`http://192.168.0.101:8383/wp-json/wp/v2/properties/?lang=en&filter[meta_query][0][key]=beds&filter[meta_query][0][value]=3&filter[meta_query][0][compare]=>=`

Kindly help to me fix on this issue or if something missed update it.

**Comment by kadamwhite** [comment] 2016-10-06 18:07
In [team discussion on 2016-09-22](https://wordpress.slack.com/archives/core-restapi/p1474581175002875) and reconfirmed on 2016-10-06, we will not be adding a `filter` shim to these endpoints. `filter` on posts is a shim that was created in v1 as a stand-in for future first-degree parameter support, which has since been built out to a substantial degree; introducing the same shim for these resources would introduce the same security, performance and future back-compatibility questions we've been working through on posts filters. This comment from @danielbachhuber hits the crux of the matter:

> As much as possible, we want to normalize parameters and usage.

Addressing @msankar1991's question, a mechanism for querying for [registered meta](https://github.com/WP-API/wp-api-meta-endpoints/pull/15) does not currently exist; while it may be added in a future release cycle, it would not be addressed by this issue (which is limited to adding `filter` to non-post resources).

**Closed as completed by kadamwhite** 2016-10-06 18:07 UTC
Labels: Discussion
