### ISSUE TITLE
Submitting duplicate comment returns HTML, not JSON

### ISSUE THREAD

**Issue by Shelob9** [WP-API/WP-API#2223] opened 2016-02-03 03:02 UTC
If I submit duplicate comment via REST API, I would expect REST API to give me a well formed error in JSON format. Instead it gives me HTML:( This is beacuse `wp_die()` is triggered here: https://github.com/WordPress/WordPress/blob/0efd5b3d001f4ec0e62afdff652cf9fb20f52718/wp-includes/comment.php#L616

Not sure if core needs a conditional there to return a `WP_Error` if `DOING_REST` or if this is a larger issue that needs addressed in `wp_die()` like the special handling for when `DOING_AJAX`

**Comment by danielbachhuber** [comment] 2016-02-03 12:37
Duplicate of #1784

**Closed as completed by danielbachhuber** 2016-02-03 12:37 UTC
