### ISSUE TITLE
Tags paging not working when fetching tags for specific post

### ISSUE THREAD

**Issue by osrecki** [WP-API/WP-API#2342] opened 2016-03-04 10:58 UTC
**Version: 2.0-beta12**

Although `tags?per_page=PER_PAGE&page=PAGE` works as expected, when fetching tags for a specific post (`tags?post=POST_ID&per_page=PER_PAGE&page=PAGE`), paging is not working at all. 

Instead, it returns all the tags for the given post, regardless of provided `PER_PAGE` and `PAGE` arguments.

**Comment by rachelbaker** [comment] 2016-03-18 20:21
@osrecki I wasn't able to reproduce this reported bug. Looks like @kjbenk could not reproduce it either.

Closing this for now. 

If you can provide more details on how we can reproduce the bug, please re-open.

**Closed as completed by rachelbaker** 2016-03-18 20:21 UTC
Labels: Bug
