### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by sirMuffles91** [WP-API/WP-API#1544] opened 2015-09-10 12:28 UTC
I am loving the plugin and it does everything I need except for outputting custom fields. We have bought a wp template and it offers featured video along side the featured image section but I am not able to get the featured video information output with wp-api. These are not the advanced custom field plugin data just a built in cutom field in the template. I installed the json-api just to test and see that it outputs the custom video field. how would I go about doing that with the wp-api?

**Comment by rachelbaker** [comment] 2015-09-20 19:07
Closing as a duplicate of #245

**Closed by rachelbaker** 2015-09-20 19:07 UTC
