### ISSUE TITLE
API has no support for POST/PUT/PATCH of multiple resources

### ISSUE THREAD

**Issue by sbussetti** [WP-API/WP-API#2719] opened 2016-09-22 17:34 UTC
Currently, the endpoint controllers base routes only support:

```
POST:  create single resource 
GET:    retrieve many resources
```

Although not explicitly outlined in most versions of a REST specification, It's common in some to allow for create, update and sometimes partial update multiple objects simultaneously.

This would extend the base route to provide the following functionality:

```
POST    <one resource>          :   create a single resource
POST    <many resources>        :   create many resources
PUT     <many resources>        :   update many resources
PATCH   <many partial resources>:   update many resources
GET                             :   retrieve many resources
```

**Comment by danielbachhuber** [comment] 2016-09-22 17:45
@sbussetti Have you seen the conversation in #561 ?

**Comment by sbussetti** [comment] 2016-09-22 17:58
@danielbachhuber Yes, I don't think this falls under the batch API as it would not allow for request batching, just simple bulk actions on lists of resources.

**Comment by sbussetti** [comment] 2016-09-22 18:00
There's an even longer discussion on the json-api boards about how to support batching and transactionality and nested resources.  I'm proposing a much simpler solution that aligns with how the WP-API is already implemented.  I need this functionality anyway, so I'll provide a PR along with documentation of the reference implementations I used as models.

**Comment by rmccue** [comment] 2016-09-22 22:08
This is a duplicate of #561.

**Closed as completed by rmccue** 2016-09-22 22:08 UTC
