### ISSUE TITLE
Cannot access all headers properties

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#2678] opened 2016-08-29 23:04 UTC
I'm trying to get the links from the response headers, I can see it when I use Postman, but in javascript I can't get it from the headers, It's not there

http://stackoverflow.com/questions/39206367/http-cannot-access-all-headers-properties

**Comment by BE-Webdesign** [comment] 2016-09-04 00:45
Hi @MurhafSousli 

Thank you for using the WP REST API.

> I'm trying to get the links from the response headers, I can see it when I use Postman, but in javascript I can't get it from the headers, It's not there

If you are doing cross domain calls you might need to specify these request headers: `Access-Control-Allow-Headers: Link` and `Access-Control-Expose-Headers: Link`.  The problem could be related to something else but try adding these request headers into your AJAX calls.

**Comment by kadamwhite** [comment] 2016-09-08 14:15
Closing as this sounds like it's a server configuration issue, not a bug with the API specifically; but please continue discussion below if needed, we can re-open it if my assumption is incorrect!

For context around the proposed solution, are you making the JS requests from within the same domain, or from an external site?

**Closed as completed by kadamwhite** 2016-09-08 14:15 UTC
Labels: Support

**Comment by MurhafSousli** [comment] 2016-09-08 14:58
Sorry for late response, I did not test your solution yet, I will confirm asap, @kadamwhite I'm doing it from an external site
