### ISSUE TITLE
Post meta permissions

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#821] opened 2015-01-30 15:23 UTC
Another problem to consider with the post meta controller: there may be fields an editor can edit that a contributor should only be able to read, or not view at all.

**Comment by rmccue** [comment] 2015-02-11 11:56
Duplicate of #504; essentially, we need the fine-grained capability check per-field of `read_post_meta` to have any wiggle room here.

**Closed by rmccue** 2015-02-11 11:56 UTC
Labels: Feedback
