### ISSUE TITLE
No response at all after a while

### ISSUE THREAD

**Issue by pimmey** [WP-API/WP-API#2324] opened 2016-02-29 09:09 UTC
I've started developing a theme using WP API, but sometimes the response is `Could not get any response` or just `Can't open page`, if in browser. After refresh it might work for a while or fail completely until I restart my local server. Got latest version of the plugin and WordPress (4.4.2). This goes to simple requests, like `wp-json/wp/v2/posts/`. 

Tried deactivating/reactivating the plugin, but nothing seems to help.

Any ideas how I could improve that?

**Comment by BE-Webdesign** [comment] 2016-02-29 15:10
@pimmey How many requests are you making at a given time?  If you could provide more information that would be helpful.  The API itself is most likely not the root cause, so deactivating and reactivating it won't do anything.

By indicating that restarting your server seems to solve the problem, I would lean towards believing that it most likely has to do with your local dev environment, machine and how performant the theme you are writing is and how those three things are interacting with each other.  If you would like to share more information I can potentially help you fix things.

**Comment by pimmey** [comment] 2016-02-29 15:22
At the moment all I do is fetch the posts and I have 2 demo posts in total. As an experiment I ran the API via Postman, without opening the web-site and it worked just fine, but about half an hour later I couldn't get any response anymore. So, there was no huge load or anything. It's all pretty random, I am not even sure what else can I say about it. Hoped for someone with a similar problem.

Then there is weird thing when there is no response in Postman, but when I open it in browser, it does work.

By the way, I'm running my local server via MAMP, PHP 5.5.26.

**Comment by BE-Webdesign** [comment] 2016-02-29 15:43
@pimmey Probably has to do with Postman then, are you using the Mac App or the Chrome App?

**Comment by jjeaton** [comment] 2016-02-29 15:46
@pimmey are you running your site over HTTPS with a self-signed certificate by chance? I've seen this happen with Postman where you have to accept the cert in Chrome before it can send requests and it only accepts it for your current session.

http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/

**Comment by pimmey** [comment] 2016-02-29 16:13
@BE-Webdesign, I'm running a Mac App I guess, not as a browser extension that is. But the API fails in browser (when I test my WP theme) as well, not only Postman.

@jjeaton, no, I'm not using HTTPS or any certificates.

**Comment by BE-Webdesign** [comment] 2016-02-29 16:40
@pimmey So every time you restart your server about a half-hour passes and you are getting errors?  Does your theme itself give you error responses as well and do other sites on your MAMP install do the same thing?

**Comment by pimmey** [comment] 2016-02-29 17:06
@BE-Webdesign, yeah, it's more or less like you described it. At first it works great, I get all the responses, but then it's just not returning anything.

Well, the theme does give me errors related to the API calls. As if the API server wasn't active.

Regarding other sites - that's my first try with WP API, other standard WP themes function just fine.

I will try to test with different environments now to eliminate this doubt.

**Comment by danielbachhuber** [comment] 2016-03-02 14:04
Feel free to continue the discussion here. Closing the issue because no action is needed within the REST API.

**Closed as completed by danielbachhuber** 2016-03-02 14:04 UTC
Labels: Support
