### ISSUE TITLE
More than ~100 posts causes internal server error with PHP FastCGI

### ISSUE THREAD

**Issue by CodeBrauer** [WP-API/WP-API#1404] opened 2015-07-15 09:23 UTC
**Reproduction:**

- Setup VM with Ubuntu 14.04 and installed simple Plesk
- Set PHP to PHP 5.5 and set the Handler to apache_mod_php
- Install Wordpress 4.2.2
- Install WP-API
- Install Quick Bulk Post & Page Creator (for faster creating 100+ posts)
- Go to Tools » Quick Post Creator & Create more than 100 posts.
- Call: `/wp-json/posts?filter[order]=ASC&filter[orderby]=name&filter[posts_per_page]=-1`
- Set handler to `fastcgi`
- Call: `/wp-json/posts?filter[order]=ASC&filter[orderby]=name&filter[posts_per_page]=-1`
- 500 Internal Server Error / Error Log says `Premature end of script headers: index.php`

You can see it here:

http://mllnm.de/wp-api/wp-json/posts?filter[order]=ASC&filter[orderby]=name&filter[posts_per_page]=-1
Just edit the `posts_per_page` param (e.g. 90 works, 120 not.).

See phpinfo() here: http://mllnm.de/info.php

**Comment by CodeBrauer** [comment] 2015-08-06 15:05
Still no response?

**Comment by rmccue** [comment] 2015-08-07 10:54
Sorry for the late response. This is a duplicate of #475, and is fixed in v2. :)

**Closed by rmccue** 2015-08-07 10:54 UTC

**Comment by CodeBrauer** [comment] 2015-08-07 13:09
Oh - just searched for fastcgi .. thanks - good to know.
