### ISSUE TITLE
Get resource content by URL

### ISSUE THREAD

**Issue by yantakus** [WP-API/WP-API#2164] opened 2016-01-30 14:12 UTC
I'm building a SPA based on WP API v2. I think this would be very easy and flexible to handle its routing like this:

When the app is initially rendered or the route has changed, we take the current path from location object and pass it to the function which fetches content from the server. For example, if the current URL is `/services/development` the request to the server would be `GET .../wp-json/wp/v2/url=services/development` (for example).

Then we would render appropriate view based on the `type` field value of the response (using a switch statement).

This would make the app very flexible and easily maintainable via the WP dashboard.

As for now, we should have different GET requests for different content types, so we should have some router configuration both server-side (WP dashboard) and client side (we should define which request to send based on the current URL). In this case it is impossible for an editor to change routing schema via WP dashboard without making the same changes to the app's router configuration.

**Comment by danielbachhuber** [comment] 2016-01-30 14:16
Duplicate of #1776

**Closed as completed by danielbachhuber** 2016-01-30 14:16 UTC
