### ISSUE TITLE
Update the image file associated with an attachment

### ISSUE THREAD

**Issue by trevordevore** [WP-API/WP-API#2824] opened 2016-10-13 15:40 UTC
Hi,

The `WP_REST_Attachments_Controller` `create_item` method will process an uploaded file and associate it with the attachment. `update_item`, however, does not look for an uploaded file. It appears that there isn't a way to update the associated attachment image file. Perhaps there is a way to update the associated image that I'm overlooking? If not, is this by design or is it just something that hasn't been implemented yet?

**Comment by danielbachhuber** [comment] 2016-10-13 15:40
> Is this by design or is it just something that hasn't been implemented yet?

I don't believe WordPress core supports this?

**Comment by trevordevore** [comment] 2016-10-13 15:44
I'm not sure. I only dabble in WordPress once in a while. `update_item` doesn't call `wp_update_post` but if it did then `wp_update_post` calls `wp_insert_attachment` which in turn calls `wp_insert_post`. `create_item` calls `wp_insert_post` which processes the uploaded file. So it seems to me that if `update_item` called `wp_update_post` and passed in the file data then the file would get updated.

**Comment by trevordevore** [comment] 2016-10-13 15:55
I'm mistaken, `update_item` does call `wp_update_post` via the `WP_REST_Posts_Controller` parent class. `update_item` isn't looking for uploaded image data like `create_item` does.

**Comment by rmccue** [comment] 2016-10-14 00:13
This is a duplicate of #2715; basically, at its core, WordPress does not support replacing existing image files.

**Closed as completed by rmccue** 2016-10-14 00:13 UTC
Labels: Support

**Comment by trevordevore** [comment] 2016-10-14 20:12
Okay. I was expecting it to as the xmlrpc interface allows you to replace images. No worries, I'll just delete images if they need updating.
