### ISSUE TITLE
Getting Error Message when I try to make an ajax call to http://wordpresssite.com/wp-json/posts

### ISSUE THREAD

**Issue by anooppete** [WP-API/WP-API#1619] opened 2015-10-01 10:48 UTC
Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (Etc/GMT+5.5)

**Comment by rachelbaker** [comment] 2015-10-05 20:55
Duplicate of #371

**Closed by rachelbaker** 2015-10-05 20:55 UTC
