### ISSUE TITLE
500 internal server error when PUT to user endpoint 

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2825] opened 2016-10-13 17:16 UTC
Here's a weird one. 

I'm getting users wp-json/wp/v2/users/17?context=edit

when I PUT  any changes to the same endpoint (minus the context=edit) wp-json/wp/v2/users/17

I get a 500 internal server error. All the other endpoints work perfectly.

Version: 2.0-beta13.1
Here's the request:
https://gist.github.com/beatelite/7008030e6a22caa2e8a18fbfa79288b0

**Comment by kadamwhite** [comment] 2016-10-14 20:37
@beatelite thanks for using the REST API, and for reporting your issue. I've been digging in to this one and so far I'm not able to reproduce. What environment are you sending the PUT request from, and what is the difference between the existing data and the updated data?

**Comment by kadamwhite** [comment] 2016-10-14 20:48
Here's the test script I used to validate the functionality is working as expected in my environment: it's a Node script because that's what I could put together fastest. It assumes that the npm package "wpapi" is installed, and was run in Node 6. The script creates a user, then attempts to PUT a new first_name property to that user. In my environment all requests succeed and the user is updated as expected; if you're still having this issue on beta 15, I'd inquire what other plugins you have running and exactly what the update you're making to the user is (it's hard to infer from the request gist).

``` js
const site = require( 'wpapi' )
    .site( 'http://local.wordpress.dev/wp-json' )
    .auth({ username: 'apiuser', password:'password' });

const user = `user${[ 0, 1, 2, 3, 4 ].map( () => {
    return Math.floor( Math.random() * 9 );
}).join( '' )}`;

let id;

site.users()
    .auth()
    .create({
        username: user,
        email: `${user}@email.com`,
        password: 'secure'
    })
    .then( u => {
        id = u.id;
        return site.users()
            .auth()
            .id( id )
            .update( Object.assign( u, {
                first_name: 'Alfred'
            }) );
    })
    .then( u => console.log( u ) )
    .catch( e => console.error( e.response && e.response.error ? JSON.parse(e.response.error.text) : e ) );
```

**Comment by nylen** [comment] 2017-01-05 23:10
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

**Closed as completed by nylen** 2017-01-05 23:10 UTC
Labels: Reporter Feedback, Support
