### ISSUE TITLE
Creating media attachment from file not working

### ISSUE THREAD

**Issue by ayublin** [WP-API/WP-API#1340] opened 2015-06-10 05:16 UTC
I have been trying to create an attachment via PHP CURL by utilizing CurlFile Class but have no luck, examining at WP-API and WP core sources, here is what I found:

Under `upload_from_file` function in `class-wp-rest-attachments-controller.php` file. The upload process is called like this:
```
$file = wp_handle_upload( $files, $overrides );
```

While in WP core's `wp-admin/includes/file.php`:
```
// @param array $file Reference to a single element of $_FILES. Call the function once for each uploaded file.
function _wp_handle_upload( &$file, $overrides, $time, $action )
```
The function works with a single elements of `$_FILES`, while the plugin passes the full array or `$_FILES`.

I suspect this is the cause, but I am aware that it may also be just my lack of knowledge on this, I searched quite extensively but found no documentation nor anyone experiencing the same thing.

**Comment by rmccue** [comment] 2015-06-12 02:46
Looks like you're right here. We should fix this. :)

**Comment by rmccue** [comment] 2015-06-12 02:56
Turns out this is a duplicate of #1303.

**Closed by rmccue** 2015-06-12 02:56 UTC
Labels: Bug

**Comment by ayublin** [comment] 2015-06-12 15:11
Ah you're right, sorry didn't found it in my search before. Thanks.
