### ISSUE TITLE
Attachments and replies in the _embedded object are showing unassociated items

### ISSUE THREAD

**Issue by scottopolis** [WP-API/WP-API#1567] opened 2015-09-18 21:20 UTC
Bug: Getting a post from /post/[id]?_embed gives you an _embedded object with attachments, replies, etc. Some of the attachments shown are not related to the post at all, as well as replies. For example, I'm seeing comments on unrelated posts under replies.

Possibly related: https://github.com/WP-API/WP-API/issues/1476

**Comment by dbtlr** [comment] 2015-09-18 21:22
I'm seeing this as well. Specifically when looking for the featured_image I need to look through the images returned to find the one that is actually associated.

**Comment by rmccue** [comment] 2015-09-22 05:50
This is a duplicate of #1476, and there's a PR at #1563.

**Closed by rmccue** 2015-09-22 05:50 UTC
