### ISSUE TITLE
search Parameter always returns 0 results

### ISSUE THREAD

**Issue by Jany-M** [WP-API/WP-API#2847] opened 2016-10-17 08:11 UTC
Using [latest](https://wordpress.org/plugins/rest-api/) `WP API v2` + `JS Backbone` [build](https://github.com/WP-API/client-js/tree/master/build/js) and I can't seem to get any results when using `search`.

My intent is to search only within titles.
My contents and excerpts are made so they are always empty (they only have a Title and custom fields).

Tried:
- `search` & `filter[s]` both return `empty`
- `s` returns `all`posts

I checked [http://demo.wp-api.org/wp-json/wp/v2/pages?s=totam](http://demo.wp-api.org/wp-json/wp/v2/pages?s=totam) and [http://demo.wp-api.org/wp-json/wp/v2/posts?s=this](http://demo.wp-api.org/wp-json/wp/v2/posts?s=this), also using `search` instead of `s`, they both return all posts, regardless the `search parameter`.

**Comment by rmccue** [comment] 2016-10-17 08:15
This [seems to be working](http://demo.wp-api.org/wp-json/wp/v2/posts?search=happened) on the demo with `search`, so I don't think this is a bug. Are you certain your search term appears in the posts you're searching for?

**Comment by Jany-M** [comment] 2016-10-17 08:19
@rmccue but why would post `"id": 455` return with search `?s=this` though?
Search should work also with titles, or does it only work with content/excerpt?

**Update**
 post `"id": 455` just disappeared from the results.... ?!

**Comment by websupporter** [comment] 2016-10-17 08:22
http://demo.wp-api.org/wp-json/wp/v2/posts?search=this

**Comment by Jany-M** [comment] 2016-10-17 08:24
Ok so I tested the demo all night and just 20 min ago and it wasn't working as expected.
Now it is. Not crazy I swear :)
Was something pushed / did something change just now?
- Should I update the plugin files with the github ones or leave the WP repo version?
- Search should work also with titles, or does it only work with content/excerpt?
- Could my issue have anything to do with the fact that my posts content is always empty?

Just to make sure my custom post is routed correctly, I tried `?slug=xxx` and it works perfectly, so are all other available parameters. Just can't seem to make `search` work.

**Comment by kadamwhite** [comment] 2016-10-17 13:43
@Jany-M nothing was changed on the demo site, and this should work the same regardless of whether you're using the latest development code from GitHub or the released plugin version. Title and content should both be getting searched, I'll do some independent testing but I don't think omitting the content should have an effect.

**Comment by kadamwhite** [comment] 2016-10-18 00:44
I've confirmed that on the latest release of WordPress and the latest beta 15 of this plugin, I can create a post with the title "only title" and no content, and it is correctly returned with `/wp/v2/posts?search=only%20title`. @Jany-M If you're still seeing irregular behavior please share some URLs that you're finding not to have the effect you'd expect, and we can try to dig deeper.

**Comment by BE-Webdesign** [comment] 2016-10-30 13:53
@Jany-M, It is also entirely possible that your WordPress install has modified how `WP_Query` searches.  I don't think there is a problem with the WordPress REST API, but depending on what other plugins are doing it could change the intended outcome of using it.

> Just to make sure my custom post is routed correctly, I tried ?slug=xxx and it works perfectly, so are all other available parameters. Just can't seem to make search work.

If you have a custom post type, you need to double check and make sure it is not excluded from search.

**Comment by nylen** [comment] 2017-01-05 23:09
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

**Closed as completed by nylen** 2017-01-05 23:09 UTC
Labels: Support
