### ISSUE TITLE
Correct search parameter for Users endpoint

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#763] opened 2015-01-05 03:35 UTC
The route docs currently gives `s` as the search parameter for the /users/ endpoint, but the correct parameter is `search` per WP_User_Query: http://codex.wordpress.org/Class_Reference/WP_User_Query#Search_Parameters

**Comment by rachelbaker** [comment] 2015-01-05 04:02
Noticed by @JasonHoffmann via Twitter: https://twitter.com/jay_hoffmann/status/551933017468731392

**Comment by danielbachhuber** [comment] 2015-01-05 16:21
This is really two things:

* [ ] We need standardize on one "search" query argument across the board. #605
* [ ] We need to auto-generate docs from our codebase.

**Comment by JasonHoffmann** [comment] 2015-01-05 16:22
@danielbachhuber way to up the game. Definitely need to standardize search.

**Comment by dleeward** [comment] 2015-01-06 20:50
This is also a duplicate of https://github.com/WP-API/WP-API/issues/763

**Comment by danielbachhuber** [comment] 2015-05-03 00:50
Handing in #924

**Closed by danielbachhuber** 2015-05-03 00:50 UTC
Labels: Bug, Documentation
