### ISSUE TITLE
\wpapi\lib\http-transport.js: Module does not exist in the module map or in these directories

### ISSUE THREAD

**Issue by geekeren** [WP-API/WP-API#3013] opened 2017-03-09 09:52 UTC
when add this library into my React Native project,,these is an error when I start ReactNative server:
>Unhandled promise rejection (rejection id: 797): UnableToResolveError: Unable to resolve module url from E:\AndroidProject\RNBlog\ReactNative\node_modules\wpapi\lib\http-transport.js: Module does not exist in the module map or in these directories:
  E:\AndroidProject\RNBlog\ReactNative\node_modules\wpapi\node_modules
,   E:\AndroidProject\RNBlog\ReactNative\node_modules

Anyone know why?

**Comment by nylen** [comment] 2017-03-09 09:55
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team

**Closed as completed by nylen** 2017-03-09 09:55 UTC

**Comment by kadamwhite** [comment] 2017-03-09 11:10
@geekeren it looks like you might have meant to post this over on https://github.com/WP-API/node-wpapi?
