### ISSUE TITLE
posts by category_name can not get exact result

### ISSUE THREAD

**Issue by lwz7512** [WP-API/WP-API#2477] opened 2016-05-03 18:34 UTC
Hi, I believe somewhere went wrong!
When visit '.../v2/posts?filter[category_name]=xxx', some posts not in category xxx return.
This occurred all the version after 2.0-beta9.

**Comment by jfalcone** [comment] 2016-05-05 13:33
So do any of the filter[category__??] filters work on V2?  It appears that they don't even with edit authorization.

**Comment by kadamwhite** [comment] 2016-05-05 14:27
This used to work so if this is the case, that is a regression

**Comment by jfalcone** [comment] 2016-05-05 16:17
Specifically I'm trying to get category__in to work with Beta 13 and the dog don't hunt.  I get all posts with no filtering happening and with proper authorization.  (I'm at a conference right now so I can't give more details).  There was an implication in a previous issues post that the category__ filters weren't implemented but I also thought that they were working earlier (Beta 12???).  I had an urgent deadline so I had to do client side category filtering in my mobile app.

**Comment by jfalcone** [comment] 2016-05-06 16:28
My specific case is that I have a set of top level categories which have no parent (parent = 0) and one of those categories has children and that's the category that I'm trying to do category__in with because I don't want the children.  But instead I'm getting all posts from all categories so it's acting like category__in isn't being applied at all.  Another possibility is that the authorization mechanism is broken but that would seem to raise a bunch of red flags.

**Comment by jfalcone** [comment] 2016-05-06 17:27
It has been very frustrating trying to move from V1 to V2 with the various changes.  V1 seemed to just work and I've had to do a lot of work in functions.php and my app to get V2 to work.  It turns out that I was having authorization problems - OK - but now that those are sorted out, I'm getting nothing returned when I apply the category__in filters regardless of whether there are posts in the category or not.

**Comment by jfalcone** [comment] 2016-05-06 17:33
Everything is OK.  It was a combination of authorization and weird category issues.  
Authorization continues to be a PITA but we're going to look at JWT next.

**Comment by BE-Webdesign** [comment] 2016-06-07 16:18
Going to close this out, as it seems to resolved.

**Closed as completed by BE-Webdesign** 2016-06-07 16:18 UTC
