### ISSUE TITLE
Cannot Comment Without Being Logged In

### ISSUE THREAD

**Issue by noamichael** [WP-API/WP-API#2960] opened 2016-12-10 17:23 UTC
Hey guys,

So, I'm using the latest version of the WP-API, and it appears that I am unable to submit a comment without being logged in. My wordpress settings allow for anyone to comment. 

My request looks like this:
    
    POST
    http://www.example.com/wp-blog/wp-json/wp/v2/comment?post=124&content=Hello_world&author_name=Me&email=Me%40example.com
    Response => {
                "code":"rest_comment_login_required",
                "message":"Sorry, you must be logged in to comment.",
                "data":{"status":401}
    }

Is there anyway to do this with the current API?

**Comment by websupporter** [comment] 2016-12-10 17:32
Hi noamichael,
anonymous comment by default is disabled with the 4.7 API. However, there is a filter, you can use:
`add_filter( 'rest_allow_anonymous_comments', '__return_true' );`

should do the trick.

**Comment by noamichael** [comment] 2016-12-10 17:37
@websupporter 

Thanks for the quick reply! Where would you add that definition? I'm not too familiar with PHP and I don't know where the standard place to add such a definition would be.

**Comment by websupporter** [comment] 2016-12-10 17:38
One place could be your (child) themes functions.php

**Comment by BE-Webdesign** [comment] 2016-12-10 17:40
@noamichael,

The best option is to create a [simple plugin file](https://developer.wordpress.org/plugins/), alternatively you can place it in a themes functions.php.  If you place the code into a theme file, when you change your active theme the functionality will be lost.

**Comment by BE-Webdesign** [comment] 2016-12-10 17:44
Closing this out as this is not a bug/enhancement for the API.  Feel free to continue discussion here.

**Closed as completed by BE-Webdesign** 2016-12-10 17:44 UTC
Labels: Support

**Comment by noamichael** [comment] 2016-12-10 17:45
@websupporter @BE-Webdesign 

Thank you for the speedy support, guys. I can now comment as expected.

**Comment by websupporter** [comment] 2016-12-10 19:25
Great :) Glad we were able to help.

**Comment by ChrisSargent** [comment] 2016-12-14 18:23
3 hours later of wondering why it wasn't working.... thanks! Might have been nice for someone to mention this: https://codex.wordpress.org/Version_4.7

**Comment by wilburx9** [comment] 2017-02-03 14:30
So how do we post the comment with the user authenticated?

**Comment by Krishna1909** [comment] 2018-03-28 04:34
Hello There, 

Very cool to see your post come up when I was searching this topic! 

[I am fairly new to Blue prism](https://asha24.com/blog/comparison-of-workfusion-vs-openspan-vs-uipath/
). I want to grade students based on their percentages, I am pulling the data from excel storing it in a collection and passing the collection's percentage field as input to the choice criterion, wherein I would compare the percentage with the range of numbers and write the grades accordingly back to the excel file in a separate column. I have not defined the structure of the collection simply for the fact that there may be hundreds if columns in an excel sheet and it won't be practical to define fields in that case, so blue prism will itself create the structure based on the excel sheet. I am using work queues.

The problem is, my collection. Percentage field is getting the data as text type but I need it to be as a number type so that I can compare it in the choice stage, I have tried to change the percentage column in excel as number but to no avail, the data still remains text type. How could I go about it?
Data from excel is of text type while in choice I need to compare it to number type?

Anyways great write up, your efforts are much appreciated. 
Regards, 
Tarun

**Comment by JennifaAfreen** [comment] 2018-03-28 11:30
Hi There, 

Thank you SO MUCH! I was actually holding my breath as I followed these directions. It worked beautifully! 
It's great to utilize the power of internet <a href="https://asha24.com/blog/openspan-introduction/"> with the available free blogs. </a> 
Appreciate your effort for making such useful blogs and helping the community. 
Regards, 
Mohith

**Comment by Krishna1909** [comment] 2018-03-29 11:09
Hello Buddie, 


10/10 !!! Thank you for making your blogs an embodiment of perfection and simplicity. You make everything so easy to follow.


Sorry, what we need is a text description of what this process shall achieve. No technical details, please. It's completely irrelevant here whether the delimiter character is a tab or a pipe or whatever; I still don't understand the logic of the whole process. Some description would help.
Please post only text, no screenshots or so. Scrolling around while reading text is not really helpful.





<a href="https://asha24.com/blog/informatica-pim-certification/">
By the way do you have </a> any YouTube videos, would love to watch it. I would like to connect you on LinkedIn, great to have experts like you in my connection (In case, if you don’t have any issues). 
Please keep providing such valuable information. 


MuchasGracias, 
Mark Hetch
