### ISSUE TITLE
get post with multiple tags and categories. Not working.

### ISSUE THREAD

**Issue by gearpichon** [WP-API/WP-API#2595] opened 2016-07-13 05:30 UTC
Hello. I want to get all the post with exactly some categories and tags, but for some reason when and do my request it just work if I use the slug of the tag and category. If I use the ids it don't work, for example:

http://server/wordpress/wp-json/wp/v2/posts?categories=4+6   //I get the "or" operation like with a "," instead a "+"

http://server/wordpress/wp-json/wp/v2/posts?filter[cat]=4+6  //also no working, empty 

http://server/wordpress/wp-json/wp/v2/posts?filter[category_and]=4,6  //not working
http://server/wordpress/wp-json/wp/v2/posts?filter[category_and]=4+6  //not working

 Same thing for the tags....but if I use directly the slug, it works, for example:

http://server/wordpress/wp-json/wp/v2/posts?filter[category_name]=cat_name+otherCat_name //only way to make it work

http://server/wordpress/wp-json/wp/v2/posts?filter[tag]=tag_name+tag_name  //only way to make it works

Maybe I am missing something in here, I hope you can help me. I want to get the post with exactly the categories and tags, sometimes I get the post I want with others extra post and that break my code (using ids).

thanks

**Comment by rachelbaker** [comment] 2016-07-26 00:15
@gearpichon Try wp-json/wp/v2/posts?filter[cat]=1&filter[cat]=2

**Comment by rachelbaker** [comment] 2016-07-31 19:17
@gearpichon  Closing this issues, as it is not a bug report.

Support questions are best addressed in the WordPress.org Support Forums (https://wordpress.org/support/) or the WordPress Stack Exchange (http://wordpress.stackexchange.com/).

**Closed as completed by rachelbaker** 2016-07-31 19:17 UTC

**Comment by vedantparchulkar** [comment] 2016-11-05 09:30
Hello, I tried it but I am getting following results: 

[Only posts from category 9 are displaying]
http://mydomain/wp-json/wp/v2/posts/?filter[cat]=13&filter[cat]=9

[Only posts from category wordpress are displaying]
http://mydomain/wp-json/wp/v2/posts/?filter[category_name]=drupal&filter[category_name]=wordpress

[Returing empty array]
http://mydomain/wp-json/wp/v2/posts/?filter[category_name]=drupal+wordpress

Is there any way tp get posts from multiple categories?

**Comment by gearpichon** [comment] 2016-11-06 02:44
hello! 

   I had the same problem. Your should try use "%2C" instead of  "," (without the quotes) and "%2B" instead of "+". For example your last query will be in this way:   

http://mydomain/wp-json/wp/v2/posts/?filter[category_name]=drupal%2Bwordpress

that should work! let me know if you have more problems.

**Comment by kadamwhite** [comment] 2016-11-06 02:50
I'd note that `filter` is not the recommended way to query for taxonomy tagged resources, and I believe filter itself is not part of the API that will be part of WordPress Core and that it will require a separate plugin to use filter. For a solution that works with both the plugin and the core API endpoints use

```
categories[]=13&categories[]=9
```

?tags will also work (with tag IDs), as will any API-registered custom taxonomy.

**Comment by kadamwhite** [comment] 2016-11-06 02:57
**Note:** edited to indicate `categories` and `tags`, not `category`: use the `rest_base` of your registered taxonomy, which will usually be the plural form.

**Comment by vedantparchulkar** [comment] 2016-11-06 04:57
Hello,
For displaying multiple categories : 
http://mydomain/wp-json/wp/v2/posts/?filter[category_name]=drupal,wordpress
this worked for me.
Thank you everyone for your help. :+1:
