### ISSUE TITLE
status=draft returning auto-draft posts

### ISSUE THREAD

**Issue by wkw** [WP-API/WP-API#2889] opened 2016-10-20 15:50 UTC
I'm seeing `auto-draft` posts leak when making a request for `status=publish,draft`. I haven't had the time yet to trace the rest api code and figure out why that's happening. I'm wondering if anyone else has possibly seen this. 

Plugin version:  **2.0-beta13**

URL: http://domain.com/wp-json/wp/v2/posts?filter[posts_per_page]=10&filter[offset]=0&status=publish,draft

and here's the first response I get back (we do some filtering on what's returned from the API so it likely does not contain all the standard response fields)

```
{
  "id": 3789,
  "date": "2016-10-20T11:11:43",
  "modified": "2016-10-20T11:11:43",
  "slug": "",
  "type": "post",
  "link": "<redacted>",
  "title": {
  "rendered": "Auto Draft"
  },
  "excerpt": {
  "rendered": ""
  },
  "author": 1,
  "featured_media": 0,
  "sticky": false,
  "format": "standard",
  "status": "auto-draft",
},
```

Look at last field there, `status`, which my filter sets with:
`$response->data['status'] = $post->post_status;`

My question is how are `auto-draft` posts ending up in that API request.
(also posted to slack channel https://wordpress.slack.com/archives/core-restapi/p1476975790009158)

[**edit**] in case it's relevant, authentication is via basic auth and https://github.com/WP-API/Basic-Auth

**Comment by joehoyle** [comment] 2016-10-20 15:56
@wkw did you try the latest version of the plugin at https://github.com/WP-API/WP-API/releases ?

**Comment by wkw** [comment] 2016-10-20 16:02
I will do that now. I reviewed previously, release notes between my b13 and latest and nothing jumped out at me. Nonetheless, composer installing it now and retesting. Thank you for the suggestion.

**Comment by wkw** [comment] 2016-10-20 16:19
@joehoyle installed `2.0-beta15` (replacing b13) and doesn’t seem to change the response. still getting two `auto-draft` posts in my response. As discussed in Slack, I either need to run against a new install or start tracing plugin code.

**Comment by joehoyle** [comment] 2016-10-20 17:05
Core patch: https://github.com/danielbachhuber/wordpress-develop/pull/4

**Comment by wkw** [comment] 2016-10-20 17:06
Nice! (patch above)
Was just in process of seeing if I could slip something like this in:
`filter[post_status]=publish&filter[post_status]=draft`

[edit] seems not. I think the last filter is the one that gets used.

**Comment by kadamwhite** [comment] 2016-10-20 18:53
@wkw I'd avoid using `filter` since it's on the chopping block for core, and would be available as a plugin—I'm hoping to get something like that in for `?status` tho

**Comment by beatelite** [comment] 2016-10-22 02:24
What do you recommend instead of filter? I'm surprised to hear this on the chopping block - don't get me wrong, I hate having to use brackets in the requests but still surprised since we've been rolling with this for so long.

**Comment by nylen** [comment] 2017-01-05 23:08
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

If you're able to identify clear steps to reproduce the bug from a clean install of WordPress 4.7, please post a Trac ticket at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

**Closed as completed by nylen** 2017-01-05 23:08 UTC
