### ISSUE TITLE
WP_REST_Controller->get_context_param( ) throws fatal error on custom endpoint after updating to WP 4.7

### ISSUE THREAD

**Issue by laustdeleuran** [WP-API/WP-API#2951] opened 2016-12-07 19:26 UTC
After updating to WP 4.7 I'm getting this error on the `/wp-json/wp/v2/pages` endpoint:

	Fatal error: Call to a member function get_field_schema() on null in /SITE_PATH/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php on line 1931
	Call Stack
	#	Time	Memory	Function	Location
	1	0.0013	233472	{main}( )	.../index.php:0
	2	0.0015	236352	require( '/SITE_PATH/wordpress/wp-blog-header.php' )	.../index.php:17
	3	0.3908	28100728	wp( )	.../wp-blog-header.php:16
	4	0.3908	28100944	WP->main( )	.../functions.php:955
	5	0.3909	28102416	WP->parse_request( )	.../class-wp.php:733
	6	0.3918	28145176	do_action_ref_array( )	.../class-wp.php:386
	7	0.3918	28145400	WP_Hook->do_action( )	.../plugin.php:515
	8	0.3918	28145496	WP_Hook->apply_filters( )	.../class-wp-hook.php:323
	9	0.3918	28146648	call_user_func_array:{/SITE_PATH/wordpress/wp-includes/class-wp-hook.php:298} ( )	.../class-wp-hook.php:298
	10	0.3918	28147120	rest_api_loaded( )	.../class-wp-hook.php:298
	11	0.3918	28147152	rest_get_server( )	.../rest-api.php:256
	12	0.3918	28149680	do_action( )	.../rest-api.php:414
	13	0.3918	28150304	WP_Hook->do_action( )	.../plugin.php:453
	14	0.3918	28150400	WP_Hook->apply_filters( )	.../class-wp-hook.php:323
	15	0.4259	28905680	call_user_func_array:{/SITE_PATH/wordpress/wp-includes/class-wp-hook.php:298} ( )	.../class-wp-hook.php:298
	16	0.4259	28906056	rev_add_rest_single( )	.../class-wp-hook.php:298
	17	0.4259	28906560	REV_Post_Single->register_routes( )	.../_rest-single.php:64
	18	0.4259	28908616	WP_REST_Controller->get_context_param( )	.../_rest-single.php:51
	19	0.4260	28910232	WP_REST_Posts_Controller->get_item_schema( )	.../class-wp-rest-controller.php:361

These are the plugins I have installed: https://cl.ly/1s1w3h0I3K2a

Help! :)

**Comment by nylen** [comment] 2016-12-07 19:52
Hi @laustdeleuran please try disabling your plugins to find the culprit.  After that you'll want to contact the author(s) of the plugin(s) responsible.

**Comment by BE-Webdesign** [comment] 2016-12-07 20:26
@laustdeleuran Follow jnylen's tips and you should be able to find the culprit. If you have any other issues feel free to continue the discussion the ticket.  Closing as the API is working on 4.7 as intended.  Most likely a hook is causing things to go awry.

**Closed as completed by BE-Webdesign** 2016-12-07 20:26 UTC
Labels: Support

**Comment by laustdeleuran** [comment] 2016-12-07 22:35
Tracked the error to this part of my theme, where I create a new endpoint using the `WP_REST_Posts_Controller` class:

```php
<?php
/**
 * Custom endpoint for WP API to allow looking up single posts across post types in ACF data
 *
 * @source http://v2.wp-api.org/extending/adding/
 * @package functions
 */

if (class_exists('WP_REST_Posts_Controller')) {



	class THEME_Post_Single extends WP_REST_Posts_Controller {

		public function __construct() {
			$this->post_type = 'post';
			$this->namespace = 'rev/v1';
			$obj = get_post_type_object( $this->post_type );
			$this->rest_base = 'single';
		}

		/**
		 * Get a single post.
		 *
		 * @param WP_REST_Request $request Full details about the request.
		 * @return WP_Error|WP_REST_Response
		 */
		public function get_item( $request ) {
			$id = (int) $request['id'];
			$post = $this->get_post( $id );

			if ( empty( $id ) || empty( $post->ID ) ) {
				return new WP_Error( 'rest_post_invalid_id', __( 'Invalid post id.' ), array( 'status' => 404 ) );
			}

			$data = $this->prepare_item_for_response( $post, $request );
			$response = rest_ensure_response( $data );

			return $response;
		}

		/**
		 * Register the routes for the objects of the controller.
		 */
		public function register_routes() {
			register_rest_route($this->namespace, '/' . $this->rest_base . '/(?P<id>[\d]+)', array(
				'methods' => WP_REST_Server::READABLE,
				'callback' => array($this, 'get_item'),
				'permission_callback' => array($this, 'get_item_permissions_check'),
				'args' => array(
					'context'  => $this->get_context_param( array( 'default' => 'view' ) ),
					'password' => array(
						'description' => __( 'The password for the post if it is password protected.' ),
					),
				)
			));
		}
	}


	// Add single endpoint
	function rev_add_rest_single() {
		$controller = new THEME_Post_Single();
		$controller->register_routes();
	}
	add_action('rest_api_init', 'rev_add_rest_single');



}
```

Search continues. Pointers much appreciated.

**Comment by laustdeleuran** [comment] 2016-12-07 22:48
So the _culprit_ was this line:

```php
'context'  => $this->get_context_param( array( 'default' => 'view' ) )
```

Specifically the `$this->get_context_param()` call. Removing the call and just referencing the array directly fixed everything.

<del>I'm certain I got that code from [the documentation](http://v2.wp-api.org/extending/adding/), but reading the documentation now that method is gone. </del> Apparently I got that code from the source code of `WP_REST_Posts_Controller`. 

@BE-Webdesign, I'm pretty sure I that the problem is because I'm calling a method that used exist in the part of WP-API that now resides in the core, but apparently has been removed or changed in 4.7. So the error is directly related to this plugin and the 4.7 update, but if you follow the current docs, you shouldn't have any issues. However, anybody who looked at the <del>docs</del> source code 3-4 months ago might experience something like this, afaik. I don't know if there's an easy way to address that.

Thanks!

**Comment by laustdeleuran** [comment] 2016-12-07 23:05
So a little more research and I find some more errors in the above code. I think the main problem is that some of the API surrounding the `WP_REST_Posts_Controller` class changed, so my extension on that also failed miserably. I need to extend that, because it does some pretty nifty JSON formatting that I didn't want to replicate in my own code, so it was much easier (and DRYer) to inherit it from the class. 

Updated my post above to reflect my new findings.
